# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a7e97e18154192a0ed9a965b9adca1f68c6e0580070eaa0a8eaa7e1c1bc4187a207023cd6d3aaa430041d5a70222e102719b0ecc60252308b500ad0be0a043

test:
  secret_key_base: 906420ddeae9292ebaca33b1c37f335cbeca999c802dabe6ac7d1128e679240f0b17f2727258f692c2cec6e3b8c0d2328028ad8d26011d8abe7a03a393ae6c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
